version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "root"
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./data/clickhouse:/var/lib/clickhouse
    restart: unless-stopped
    networks:
      - mutagen-backend

  grafana:
    build:
      context: ./docker_files/
      dockerfile: grafana.Dockerfile
    user: "root"
    container_name: grafana
    hostname: grafana
    volumes:
      - ./fs/volumes/grafana/etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
    depends_on:
      - clickhouse
    restart: unless-stopped
    networks:
      - mutagen-backend

networks:
  mutagen-backend:
    external: true
    name: mutagen-backend
