apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutagen-clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server
          ports:
            - containerPort: 8123
            - containerPort: 9000
          volumeMounts:
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/config.d
            - name: clickhouse-users
              mountPath: /etc/clickhouse-server/users.d
            - name: clickhouse-entrypoint
              mountPath: /docker-entrypoint-initdb.d
          securityContext:
            runAsUser: 101
            runAsGroup: 101
      volumes:
        - name: clickhouse-config
          hostPath:
            path: "$(PWD)/fs/volumes/clickhouse/etc/clickhouse-server/config.d"
        - name: clickhouse-users
          hostPath:
            path: "$(PWD)/fs/volumes/clickhouse/etc/clickhouse-server/users.d"
        - name: clickhouse-entrypoint
          hostPath:
            path: "$(PWD)/entrypoint.sh"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutagen-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: your-grafana-image:tag
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-datasources
          hostPath:
            path: "$(PWD)/fs/volumes/grafana/etc/grafana/provisioning/datasources"
