FROM grafana/grafana-enterprise:latest

ENV GF_SECURITY_ALLOW_EMBEDDING=true
ENV GF_AUTH_ANONYMOUS_ENABLED=false

ENV GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
ENV GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

ENV GF_INSTALL_PLUGINS=grafana-clickhouse-datasource

EXPOSE 3000
