apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse
      username: default
      password: iyLOLr1EXIWin8z4zMNe3UFKJ5qoba
      tlsSkipVerify: false